version: '3.5'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - '1025:1025'
      - '8025:8025'
volumes:
  nest-auth-db:
